"""Public completion facade.

Provides the stable `bywaf.completion` import path for readline integration,
prompt-toolkit integration, and lower-level candidate generation helpers.

Used by:
- REPL shell: installs interactive completion.
- completion tests and plugins: import a stable completion API."""

from __future__ import annotations

from .facade import (
    BINARY_OPTION_NAMES,
    COMPLETION_SELECT_KEY_VAR,
    COMPLETION_WASD_SELECTION_VAR,
    DEFAULT_COMPLETION_SELECT_KEY,
    DEFAULT_SECRET_INPUT_MODE,
    SECRET_INPUT_MODES,
    SECRET_INPUT_MODE_VAR,
    Completer,
    CoreCompleter,
    PromptToolkitCompleter,
    apply_current_completion,
    build_prompt_session,
    bundle_candidates,
    cancel_completion_menu,
    common_completion_prefix,
    complete_at_file_prefix,
    complete_resource_value,
    completion_key_bindings,
    completion_prefix,
    completion_results,
    completion_select_key,
    completion_select_key_display,
    completion_wasd_selection_enabled,
    configure_readline_delimiters,
    display_label,
    enter_completion_selection_mode,
    format_candidate,
    framework_bool,
    history_candidates,
    install_readline,
    is_explicit_path,
    key_candidates,
    option_is_binary,
    positional_index,
    preserve_explicit_prefix,
    print_completion_menu,
    prompt_toolkit_available,
    readline,
    register_select_completion_binding,
    register_wasd_completion_bindings,
    resource_candidates,
    runtime_completion_target,
    secret_input_bottom_toolbar,
    secret_input_mode,
    should_display_value_only,
    should_print_completion_menu,
    tokens_after_last_pipe,
    variable_reference_candidates,
)

__all__ = [
    "BINARY_OPTION_NAMES",
    "COMPLETION_SELECT_KEY_VAR",
    "COMPLETION_WASD_SELECTION_VAR",
    "DEFAULT_COMPLETION_SELECT_KEY",
    "DEFAULT_SECRET_INPUT_MODE",
    "SECRET_INPUT_MODES",
    "SECRET_INPUT_MODE_VAR",
    "Completer",
    "CoreCompleter",
    "PromptToolkitCompleter",
    "apply_current_completion",
    "build_prompt_session",
    "bundle_candidates",
    "cancel_completion_menu",
    "common_completion_prefix",
    "complete_at_file_prefix",
    "complete_resource_value",
    "completion_key_bindings",
    "completion_prefix",
    "completion_results",
    "completion_select_key",
    "completion_select_key_display",
    "completion_wasd_selection_enabled",
    "configure_readline_delimiters",
    "display_label",
    "enter_completion_selection_mode",
    "format_candidate",
    "framework_bool",
    "history_candidates",
    "install_readline",
    "is_explicit_path",
    "key_candidates",
    "option_is_binary",
    "positional_index",
    "preserve_explicit_prefix",
    "print_completion_menu",
    "prompt_toolkit_available",
    "readline",
    "register_select_completion_binding",
    "register_wasd_completion_bindings",
    "resource_candidates",
    "runtime_completion_target",
    "secret_input_bottom_toolbar",
    "secret_input_mode",
    "should_display_value_only",
    "should_print_completion_menu",
    "tokens_after_last_pipe",
    "variable_reference_candidates",
]
