"""Interactive REPL shell orchestration.

Provides ShellState, prompt/input handling, command-history recording,
line dispatch, and non-interactive `bywaf exec` helpers. Built-in command
behavior, display formatting, and load/save resources live in sibling modules.

Used by:
- bywaf.repl.__init__: re-exports the public REPL API for compatibility.
- bywaf.app: starts repl() and calls run_remainder() for CLI execution.
- bywaf.repl.resources: calls dispatch helpers when running script files."""


from __future__ import annotations

import os
import platform
import shlex
import socket
import sys
import termios
import tty
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from ..completion import Completer, build_prompt_session, install_readline
from ..framework_requests import process_framework_requests
from .commands import (
    REPL_COMMAND_HANDLERS,
    execute_repl_commandlet,
    execute_shell_command,
    visible_commandlet_events,
)
from .display import (
    friendly_error,
)
from .preferences import apply_preferences, ensure_preferences_file, load_preferences, resolve_preferences_path
from ..plugins.network.nmap_backend import NmapScanError, NmapUnavailableError
from ..projects import ProjectPaths
from ..registry import PluginTrustError
from .resources import DEFAULT_HISTORY
from .scripts import strip_inline_comment
from ..runner import Runner
from ..secret.store import load_or_create_fingerprint_key, redact_command_text
from ..time_format import OPERATOR_TIMESTAMP_FORMAT
from ..triggers import disable_session_triggers, start_default_services, stop_session_services


DEFAULT_HISTORY_TIMESTAMP_FORMAT = OPERATOR_TIMESTAMP_FORMAT
HISTORY_TIMESTAMP_FORMAT_VAR = "history.timestamp-format"


@dataclass(slots=True)
class ShellState:
    """Mutable REPL-only state that should not live in the database."""

    prompt_pattern: str = "$Y$M$D $h:$m:$s $Z%F> "
    history_path: Path = field(default_factory=lambda: DEFAULT_HISTORY)
    session_history: list[str] = field(default_factory=list)
    handled_request_ids: set[int] = field(default_factory=set)
    framework_request_after_id: int = 0
    active_context: str | None = None
    completer: Completer | None = None
    secret_values: dict[str, str] = field(default_factory=dict)

    def prompt(self) -> str:
        return render_prompt(self.prompt_pattern, active_context=self.active_context)


def shutdown_runner(runner: Runner) -> None:
    """Flush SQLite WAL state before the process exits."""

    # Stop services before checkpointing so background framework work has a
    # chance to finish writing its final lifecycle events.
    stop_session_services(runner)
    disable_session_triggers(runner)
    runner.maintenance.checkpoint()


def repl(runner: Runner) -> None:
    """Run the interactive shell until EOF, interrupt, or an exit command."""

    state = new_shell_state(runner)
    apply_startup_preferences(runner, state)
    state.completer = Completer(runner.registry, runner.db)
    input_reader = build_input_reader(state.completer, state)
    start_default_services(runner)
    try:
        while True:
            # Framework requests are event-driven UI side effects such as
            # console output/alerts emitted by background jobs.
            process_framework_requests(runner, state)
            start_default_services(runner)
            try:
                line = read_logical_input(state, input_reader).strip()
            except EOFError:
                print()
                if confirm_repl_exit(input_reader):
                    return
                continue
            except KeyboardInterrupt:
                print()
                if confirm_repl_exit(input_reader):
                    return
                continue
            record_command_history(
                line,
                state.history_path,
                state.session_history,
                runner.registry.varstore.get(
                    HISTORY_TIMESTAMP_FORMAT_VAR,
                    DEFAULT_HISTORY_TIMESTAMP_FORMAT,
                ) or DEFAULT_HISTORY_TIMESTAMP_FORMAT,
                stored_command=redact_history_command(line),
            )
            if dispatch_repl_line(runner, line, state) == "exit":
                return
            # Drain requests generated by this foreground command before
            # showing the next prompt.
            process_framework_requests(runner, state)
    finally:
        shutdown_runner(runner)


def build_input_reader(completer: Completer, state: ShellState | None = None) -> Callable[[str], str]:
    """Return the best available line reader for the current terminal."""
    if os.environ.get("BYWAF_INPUT_READER", "").casefold() != "readline" and sys.stdin.isatty() and sys.stdout.isatty():
        session = build_prompt_session(completer)
        if session is not None:
            secret_state = getattr(session, "secret_state", None)

            def prompt_with_secret_capture(prompt: str) -> str:
                text = session.prompt(prompt)
                if state is not None and secret_state is not None:
                    # Prompt-toolkit can collect masked secret values while
                    # leaving redacted refs in the command line.
                    state.secret_values = secret_state.values_for_command(text)
                    secret_state.clear()
                return text

            return prompt_with_secret_capture
    install_readline(completer)
    return input


def confirm_repl_exit(
    reader: Callable[[str], str] | None = None,
    key_reader: Callable[[], str] | None = None,
) -> bool:
    """Ask whether Ctrl-C should exit the REPL."""
    if key_reader is not None or (sys.stdin.isatty() and sys.stdout.isatty()):
        return confirm_repl_exit_keypress(key_reader or read_single_key)
    if reader is None:
        reader = input
    while True:
        try:
            answer = reader("Quit Bywaf? [y/N] ").strip().lower()
        except KeyboardInterrupt:
            print()
            return False
        except EOFError:
            print()
            return True
        if answer in {"", "n", "no"}:
            return False
        if answer in {"y", "yes"}:
            return True
        print("please answer yes or no")


def confirm_repl_exit_keypress(key_reader: Callable[[], str]) -> bool:
    """Ask whether to exit, accepting one key without requiring Enter."""
    while True:
        print("Quit Bywaf? [y/N] ", end="", flush=True)
        key = key_reader()
        answer = key.casefold()
        if key in {"\x03"}:
            print()
            return False
        if key in {"\x04"}:
            print()
            return True
        if key in {"\r", "\n"} or answer in {"", "n"}:
            print("n" if key not in {"\r", "\n"} else "")
            return False
        if answer == "y":
            print("y")
            return True
        print()
        print("please press y or n")


def read_single_key() -> str:
    """Read one keypress from stdin without waiting for Enter."""
    fd = sys.stdin.fileno()
    previous = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        return sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, previous)


def read_logical_input(state: ShellState, reader: Callable[[str], str] | None = None) -> str:
    """Read one logical REPL command, joining backslash continuations."""
    reader = reader or input
    lines: list[str] = []
    prompt = state.prompt()
    while True:
        line = reader(prompt)
        if line_has_continuation(line):
            lines.append(remove_line_continuation(line))
            prompt = "... "
            continue
        lines.append(line)
        return "\n".join(lines)


def dispatch_repl_line(runner: Runner, line: str, state: ShellState | None = None) -> str | None:
    """Dispatch one REPL line and keep errors user-facing.

    Built-ins are handled here; commandlets fall through to the generic runner
    so plugin commands such as `ls` are not hard-coded into the shell.
    """
    state = state or ShellState(framework_request_after_id=runner.events.latest_event_id())
    line = strip_inline_comment(line)
    if not line.strip():
        return None
    commands = split_command_sequence(line)
    if len(commands) > 1:
        # Semicolon sequencing is handled at the REPL layer, not by the
        # commandlet parser, so each command gets normal built-in dispatch.
        for command in commands:
            if dispatch_repl_line(runner, command, state) == "exit":
                return "exit"
        return None
    try:
        parts = line.split(maxsplit=1)
        if not parts:
            return None
        name = parts[0]
        rest = parts[1] if len(parts) > 1 else None
        handler = REPL_COMMAND_HANDLERS.get(name)
        if handler is not None:
            return handler(runner, state, rest, line)
        if runner.registry.has_commandlet(name):
            execute_repl_commandlet(runner, state, line)
            return None
        print(f"error: unknown command or commandlet: {name}")
    except SystemExit as exc:
        if exc.code not in (0, None):
            print(f"error: command failed with exit code {exc.code}")
    except (NmapUnavailableError, NmapScanError) as exc:
        print(f"error: {exc}")
    except PluginTrustError as exc:
        print(str(exc))
    except (KeyError, ValueError) as exc:
        print(f"error: {friendly_error(exc)}")
    except Exception as exc:
        print(f"error: {exc}")
    return None


def new_shell_state(runner: Runner) -> ShellState:
    """Create shell state that ignores historical framework requests."""
    project = runner.project if isinstance(runner.project, ProjectPaths) else None
    history_path = project.history if project is not None else DEFAULT_HISTORY
    return ShellState(
        framework_request_after_id=runner.events.latest_event_id(),
        history_path=history_path,
    )


def apply_startup_preferences(runner: Runner, state: ShellState) -> None:
    """Ensure and apply user-local preferences at REPL startup."""
    path = resolve_preferences_path()
    try:
        ensure_preferences_file(path)
        apply_preferences(runner, state, load_preferences(path))
    except (OSError, ValueError) as exc:
        print(f"warning: could not load pref={path}: {friendly_error(exc)}")


def execute_and_print(runner: Runner, command: str) -> int:
    """Execute one command line for top-level `bywaf exec` callers."""
    return execute_shell_command(runner, command)


def execute_commandlet_and_print(runner: Runner, command: str) -> int:
    """Execute one commandlet line for direct non-interactive CLI callers."""
    try:
        state = new_shell_state(runner)
        events = runner.execute(command)
        process_framework_requests(runner, state)
        from .display import print_events

        print_events(visible_commandlet_events(events), runner)
    except SystemExit as exc:
        if exc.code in (0, None):
            return 0
        print(f"error: command failed with exit code {exc.code}")
        return int(exc.code) if isinstance(exc.code, int) else 1
    except (NmapUnavailableError, NmapScanError) as exc:
        print(f"error: {exc}")
        return 1
    except (KeyError, ValueError) as exc:
        print(f"error: {friendly_error(exc)}")
        return 1
    return 0


def command_from_remainder(tokens: list[str]) -> str:
    """Build a command string from argparse REMAINDER tokens.

    A single token is already a shell-preserved command string, which matters
    for quoted pipelines such as `bywaf exec 'a | b'`.
    """
    if not tokens:
        raise ValueError("exec requires a command")
    if len(tokens) == 1:
        return tokens[0]
    return " ".join(shlex.quote(token) for token in tokens)


def run_remainder(runner: Runner, tokens: list[str]) -> int:
    """Validate and run the token remainder from `bywaf exec ...`."""
    try:
        command = command_from_remainder(tokens)
    except ValueError as exc:
        print(f"error: {exc}")
        return 1
    return execute_and_print(runner, command)


def run_commandlet_remainder(runner: Runner, tokens: list[str]) -> int:
    """Validate and run direct non-interactive commandlet arguments."""
    try:
        command = command_from_remainder(tokens)
    except ValueError:
        print("error: commandlet invocation requires a command")
        return 1
    status = 0
    for one_command in split_command_sequence(command) or [command]:
        status = execute_commandlet_and_print(runner, one_command)
        if status != 0:
            return status
    return status


def split_command_sequence(line: str) -> list[str]:
    """Split pasted command sequences while preserving quoted separators."""
    commands: list[str] = []
    quote: str | None = None
    escaped = False
    current: list[str] = []
    for char in line:
        if escaped:
            current.append(char)
            escaped = False
            continue
        if char == "\\":
            current.append(char)
            escaped = True
            continue
        if quote is not None:
            current.append(char)
            if char == quote:
                quote = None
            continue
        if char in {"'", '"'}:
            current.append(char)
            quote = char
            continue
        if char in {";", "\n"}:
            # Only unquoted semicolons and newlines delimit REPL commands.
            # This makes multi-line paste behave like a tiny script without
            # making commandlet parsers handle unrelated trailing commands.
            command = "".join(current).strip()
            if command:
                commands.append(command)
            current = []
            continue
        current.append(char)
    command = "".join(current).strip()
    if command:
        commands.append(command)
    return commands


def line_has_continuation(line: str) -> bool:
    """Return whether a physical line ends with an unescaped continuation slash."""
    stripped = line.rstrip()
    backslashes = len(stripped) - len(stripped.rstrip("\\"))
    return backslashes % 2 == 1


def remove_line_continuation(line: str) -> str:
    """Remove one trailing continuation slash from a physical line."""
    stripped = line.rstrip()
    return stripped[:-1]


def record_command_history(
    command: str,
    path: Path = DEFAULT_HISTORY,
    session_history: list[str] | None = None,
    timestamp_format: str = DEFAULT_HISTORY_TIMESTAMP_FORMAT,
    stored_command: str | None = None,
) -> str | None:
    """Append a command to persistent history and the in-memory session list."""
    if not command.strip():
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    # Store the timestamp as an inline comment so history files remain readable
    # as executable scripts after stripping comments.
    timestamp = datetime.now().astimezone().strftime(timestamp_format).strip()
    entry = f"{stored_command or command}  # {timestamp}"
    with path.open("a", encoding="utf-8") as handle:
        handle.write(f"{entry}\n")
    if session_history is not None:
        session_history.append(entry)
    return entry


def redact_history_command(command: str) -> str:
    """Return a history-safe command with obvious secret assignments removed."""
    if "=" not in command:
        return command
    result = redact_command_text(command, key=load_or_create_fingerprint_key())
    return result.command


def render_prompt(pattern: str, *, active_context: str | None = None) -> str:
    """Render prompt placeholders using local process and host metadata."""
    user = os.getenv("USER", "")
    host_full = socket.gethostname()
    now = datetime.now().astimezone()
    provider, commandlet = prompt_scope_parts(active_context)
    focus = f" {active_context}" if active_context else ""
    replacements = {
        "%u": user,
        "%h": host_full.split(".", 1)[0],
        "%H": host_full,
        "%m": platform.machine(),
        "%T": now.strftime("%H:%M:%S"),
        "%p": provider,
        "%c": commandlet,
        "%P": active_context or "",
        "%F": focus,
        "$u": user,
        "$Y": now.strftime("%Y"),
        "$M": now.strftime("%m"),
        "$D": now.strftime("%d"),
        "$h": now.strftime("%H"),
        "$m": now.strftime("%M"),
        "$s": now.strftime("%S"),
        "$Z": now.strftime("%Z"),
    }
    prompt = pattern
    for key, value in replacements.items():
        prompt = prompt.replace(key, value)
    return prompt


def prompt_scope_parts(active_context: str | None) -> tuple[str, str]:
    """Return provider and commandlet prompt fields for the current focus."""
    if not active_context:
        return "", ""
    provider, separator, commandlet = active_context.rpartition("/")
    if not separator:
        return active_context, ""
    return provider, commandlet
