"""Interactive REPL shell orchestration.

Provides ShellState, prompt/input handling, command-history recording,
line dispatch, and non-interactive `bywaf exec` helpers. Built-in command
behavior, display formatting, and load/save resources live in sibling modules.

Used by:
- bywaf.repl.__init__: re-exports the public REPL API for compatibility.
- bywaf.app: starts repl() and calls run_remainder() for CLI execution.
- bywaf.repl.dispatch: owns built-in command routing."""


from __future__ import annotations

import os
import signal
import sys
import termios
import tty
from collections.abc import Callable
from datetime import datetime
from pathlib import Path

from ..completion import Completer, build_prompt_session, install_readline
from ..framework_requests import process_framework_requests
from .commands import execute_shell_command, visible_commandlet_events
from .dispatch import dispatch_repl_line
from .display import (
    friendly_error,
)
from .parsing import command_from_remainder, line_has_continuation, remove_line_continuation, split_command_sequence
from .preferences import apply_preferences, ensure_preferences_file, load_preferences, resolve_preferences_path
from ..plugins.network.nmap_backend import NmapScanError, NmapUnavailableError
from ..runner import Runner
from ..secret.store import load_or_create_fingerprint_key, redact_command_text
from .resource_specs import DEFAULT_HISTORY
from .state import DEFAULT_HISTORY_TIMESTAMP_FORMAT, HISTORY_TIMESTAMP_FORMAT_VAR, ShellState, new_shell_state, render_prompt
from ..triggers import disable_session_triggers, start_default_services, stop_session_services


def shutdown_runner(runner: Runner) -> None:
    """Flush SQLite WAL state before the process exits."""

    # Stop services before checkpointing so background framework work has a
    # chance to finish writing its final lifecycle events.
    stop_session_services(runner)
    disable_session_triggers(runner)
    runner.maintenance.checkpoint()


def repl(runner: Runner) -> None:
    """Run the interactive shell until EOF, interrupt, or an exit command."""

    state = new_shell_state(runner)
    apply_startup_preferences(runner, state)
    state.completer = Completer(runner.registry, runner.db)
    input_reader = build_input_reader(state.completer, state)
    start_default_services(runner)
    suspend_handler = install_shell_suspend_handler()
    try:
        while True:
            # Framework requests are event-driven UI side effects such as
            # console output/alerts emitted by background jobs.
            process_framework_requests(runner, state)
            start_default_services(runner)
            try:
                line = read_logical_input(state, input_reader).strip()
            except EOFError:
                print()
                if confirm_repl_exit(input_reader):
                    return
                continue
            except KeyboardInterrupt:
                print()
                if confirm_repl_exit(input_reader):
                    return
                continue
            record_command_history(
                line,
                state.history_path,
                state.session_history,
                runner.registry.varstore.get(
                    HISTORY_TIMESTAMP_FORMAT_VAR,
                    DEFAULT_HISTORY_TIMESTAMP_FORMAT,
                ) or DEFAULT_HISTORY_TIMESTAMP_FORMAT,
                stored_command=redact_history_command(line),
            )
            if dispatch_repl_line(runner, line, state) == "exit":
                return
            # Drain requests generated by this foreground command before
            # showing the next prompt.
            process_framework_requests(runner, state)
    finally:
        restore_shell_suspend_handler(suspend_handler)
        shutdown_runner(runner)


def build_input_reader(completer: Completer, state: ShellState | None = None) -> Callable[[str], str]:
    """Return the best available line reader for the current terminal."""
    if os.environ.get("BYWAF_INPUT_READER", "").casefold() != "readline" and sys.stdin.isatty() and sys.stdout.isatty():
        session = build_prompt_session(completer)
        if session is not None:
            secret_state = getattr(session, "secret_state", None)

            def prompt_with_secret_capture(prompt: str) -> str:
                text = session.prompt(prompt)
                if state is not None and secret_state is not None:
                    # Prompt-toolkit can collect masked secret values while
                    # leaving redacted refs in the command line.
                    state.secret_values = secret_state.values_for_command(text)
                    secret_state.clear()
                return text

            return prompt_with_secret_capture
    install_readline(completer)
    return input


def install_shell_suspend_handler():
    """Install a Ctrl-Z handler for interactive Unix shells."""
    sigtstp = getattr(signal, "SIGTSTP", None)
    if sigtstp is None or not sys.stdin.isatty() or not sys.stdout.isatty():
        return None
    previous = signal.signal(sigtstp, suspend_to_shell)
    return sigtstp, previous


def restore_shell_suspend_handler(handler) -> None:
    """Restore the Ctrl-Z handler captured by install_shell_suspend_handler."""
    if handler is None:
        return
    signum, previous = handler
    signal.signal(signum, previous)


def suspend_to_shell(signum, frame) -> None:
    """Announce and delegate Ctrl-Z to normal terminal job control."""
    del frame
    print('\nDropping to shell; enter "fg" to resume.', flush=True)
    signal.signal(signum, signal.SIG_DFL)
    try:
        os.killpg(os.getpgrp(), signum)
    except OSError:
        os.kill(os.getpid(), signum)
    signal.signal(signum, suspend_to_shell)


def confirm_repl_exit(
    reader: Callable[[str], str] | None = None,
    key_reader: Callable[[], str] | None = None,
) -> bool:
    """Ask whether Ctrl-C should exit the REPL."""
    if key_reader is not None or (sys.stdin.isatty() and sys.stdout.isatty()):
        return confirm_repl_exit_keypress(key_reader or read_single_key)
    if reader is None:
        reader = input
    while True:
        try:
            answer = reader("Quit Bywaf? [y/N] ").strip().lower()
        except KeyboardInterrupt:
            print()
            return False
        except EOFError:
            print()
            return True
        if answer in {"", "n", "no"}:
            return False
        if answer in {"y", "yes"}:
            return True
        print("please answer yes or no")


def confirm_repl_exit_keypress(key_reader: Callable[[], str]) -> bool:
    """Ask whether to exit, accepting one key without requiring Enter."""
    while True:
        print("Quit Bywaf? [y/N] ", end="", flush=True)
        key = key_reader()
        answer = key.casefold()
        if key in {"\x03"}:
            print()
            return False
        if key in {"\x04"}:
            print()
            return True
        if key in {"\r", "\n"} or answer in {"", "n"}:
            print("n" if key not in {"\r", "\n"} else "")
            return False
        if answer == "y":
            print("y")
            return True
        print()
        print("please press y or n")


def read_single_key() -> str:
    """Read one keypress from stdin without waiting for Enter."""
    fd = sys.stdin.fileno()
    previous = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        return sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, previous)


def read_logical_input(state: ShellState, reader: Callable[[str], str] | None = None) -> str:
    """Read one logical REPL command, joining backslash continuations."""
    reader = reader or input
    lines: list[str] = []
    prompt = state.prompt()
    while True:
        line = reader(prompt)
        if line_has_continuation(line):
            lines.append(remove_line_continuation(line))
            prompt = "... "
            continue
        lines.append(line)
        return "\n".join(lines)


def apply_startup_preferences(runner: Runner, state: ShellState) -> None:
    """Ensure and apply user-local preferences at REPL startup."""
    path = resolve_preferences_path()
    try:
        ensure_preferences_file(path)
        apply_preferences(runner, state, load_preferences(path))
    except (OSError, ValueError) as exc:
        print(f"warning: could not load pref={path}: {friendly_error(exc)}")


def execute_and_print(runner: Runner, command: str) -> int:
    """Execute one command line for top-level `bywaf exec` callers."""
    return execute_shell_command(runner, command)


def execute_commandlet_and_print(runner: Runner, command: str) -> int:
    """Execute one commandlet line for direct non-interactive CLI callers."""
    try:
        state = new_shell_state(runner)
        events = runner.execute(command)
        process_framework_requests(runner, state)
        from .display import print_events

        print_events(visible_commandlet_events(events), runner)
    except SystemExit as exc:
        if exc.code in (0, None):
            return 0
        print(f"error: command failed with exit code {exc.code}")
        return int(exc.code) if isinstance(exc.code, int) else 1
    except (NmapUnavailableError, NmapScanError) as exc:
        print(f"error: {exc}")
        return 1
    except (KeyError, ValueError) as exc:
        print(f"error: {friendly_error(exc)}")
        return 1
    return 0


def run_remainder(runner: Runner, tokens: list[str]) -> int:
    """Validate and run the token remainder from `bywaf exec ...`."""
    try:
        command = command_from_remainder(tokens)
    except ValueError as exc:
        print(f"error: {exc}")
        return 1
    return execute_and_print(runner, command)


def run_commandlet_remainder(runner: Runner, tokens: list[str]) -> int:
    """Validate and run direct non-interactive commandlet arguments."""
    try:
        command = command_from_remainder(tokens)
    except ValueError:
        print("error: commandlet invocation requires a command")
        return 1
    status = 0
    for one_command in split_command_sequence(command) or [command]:
        status = execute_commandlet_and_print(runner, one_command)
        if status != 0:
            return status
    return status


def record_command_history(
    command: str,
    path: Path = DEFAULT_HISTORY,
    session_history: list[str] | None = None,
    timestamp_format: str = DEFAULT_HISTORY_TIMESTAMP_FORMAT,
    stored_command: str | None = None,
) -> str | None:
    """Append a command to persistent history and the in-memory session list."""
    if not command.strip():
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    # Store the timestamp as an inline comment so history files remain readable
    # as executable scripts after stripping comments.
    timestamp = datetime.now().astimezone().strftime(timestamp_format).strip()
    entry = f"{stored_command or command}  # {timestamp}"
    with path.open("a", encoding="utf-8") as handle:
        handle.write(f"{entry}\n")
    if session_history is not None:
        session_history.append(entry)
    return entry


def redact_history_command(command: str) -> str:
    """Return a history-safe command with obvious secret assignments removed."""
    if "=" not in command:
        return command
    result = redact_command_text(command, key=load_or_create_fingerprint_key())
    return result.command
