#!/usr/bin/env python3
"""Create a minimal plugin scaffold.

Generates the smallest native Bywaf plugin shapes intended for new plugin
authors and AI-assisted plugin drafts. The generated plugin is manifest-backed
and should pass the relevant validation before any real logic is added.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


IDENTIFIER_RE = re.compile(r"^[a-z][a-z0-9_]*$")
TOPIC_RE = re.compile(r"^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*$")


def validate_identifier(value: str, *, label: str) -> str:
    """Return a valid Bywaf/Python identifier or raise ArgumentTypeError."""
    if not IDENTIFIER_RE.fullmatch(value):
        raise argparse.ArgumentTypeError(
            f"{label} must match {IDENTIFIER_RE.pattern}; use lowercase snake_case"
        )
    return value


def validate_topic(value: str) -> str:
    """Return a valid dotted event topic or raise ArgumentTypeError."""
    if not TOPIC_RE.fullmatch(value):
        raise argparse.ArgumentTypeError(
            f"topic must match {TOPIC_RE.pattern}; use lowercase dotted names"
        )
    return value


def class_name(identifier: str) -> str:
    """Return a readable test class name for a snake_case identifier."""
    return "".join(part.capitalize() for part in identifier.split("_")) or "Plugin"


def toml_string(value: str) -> str:
    """Return a TOML-compatible basic string literal."""
    return json.dumps(value)


def plugin_py(commandlet: str, argument: str, topic: str, *, bundled: bool = False) -> str:
    """Return the generated plugin Python content."""
    module_kind = "bundled" if bundled else "filesystem"
    return f'''"""Generated Bywaf plugin scaffold for {commandlet}."""

from bywaf.plugin import Commandlet, commandlet


@commandlet
def {commandlet}(context, cfg, input_events):
    """Emit a small structured {module_kind} observation for one target."""
    del context
    del input_events

    yield {{
        "{argument}": cfg.{argument},
        "status": "observed",
    }}


def plugin() -> Commandlet:
    """Factory used by Bywaf plugin loading."""
    return {commandlet}
'''


def manifest_toml(
    commandlet: str,
    argument: str,
    topic: str,
    *,
    description: str,
    version: str,
    module: str = "",
) -> str:
    """Return the generated bywaf.plugin.toml content."""
    quoted_version = toml_string(version)
    quoted_description = toml_string(description)
    module_line = f'module = "{module}"\n' if module else ""
    return f'''[plugin]
version = {quoted_version}
native = true
library_backed = false
process_wrapped = false
service = false
roles = ["command-provider"]

[[commandlets]]
name = "{commandlet}"
description = {quoted_description}
usage = "{commandlet} <{argument}>"
examples = [
  "{commandlet} example.test",
]
emits = ["{topic}"]
capabilities = []
{module_line}database.actions.view = false
database.actions.write = true
database.actions.manage = false

[[commandlets.arguments]]
name = "{argument}"
description = "Target value to process"

[[event_schemas]]
topic = "{topic}"
version = "1"
summary = "Structured observation emitted by {commandlet}."

[[event_schemas.fields]]
name = "{argument}"
type = "str"
required = true
description = "Target value that was processed."

[[event_schemas.fields]]
name = "status"
type = "str"
required = true
description = "Observation status."
'''


def test_py(commandlet: str, argument: str, topic: str) -> str:
    """Return a generated smoke test for the plugin commandlet."""
    test_class = class_name(commandlet)
    return f'''import unittest
from unittest import mock

from plugin import plugin


class {test_class}Tests(unittest.TestCase):
    def test_emits_observation_payload(self):
        commandlet = plugin()

        events = list(commandlet.run(mock.MagicMock(), ["example.test"], []))

        self.assertEqual(commandlet.spec.name, "{commandlet}")
        self.assertEqual(commandlet.spec.emits, ("{topic}",))
        self.assertEqual(events, [{{"{argument}": "example.test", "status": "observed"}}])


if __name__ == "__main__":
    unittest.main()
'''


def readme_md(commandlet: str, argument: str, topic: str) -> str:
    """Return a small README for the generated plugin."""
    return f'''# {commandlet}

Generated Bywaf filesystem plugin scaffold.

## Validate

```bash
python3 scripts/plugin_check.py path/to/{commandlet} --strict-inference --llm-feedback
PYTHONPATH=path/to/{commandlet} python3 -m unittest discover -s path/to/{commandlet}/tests
```

## Where To Put Code

- Put the commandlet's first implementation inside `{commandlet}(...)` in
  `plugin.py`.
- Replace the placeholder yielded payload with the structured fact this plugin
  owns.
- If the logic grows, move pure parsing/probing code into helper functions or
  split files such as `detect.py`, then keep `plugin.py` as the thin commandlet
  entry point.
- Keep `bywaf.plugin.toml` synchronized with the commandlet: arguments,
  emitted topics, capabilities, database actions, and event schema fields.
- Update `tests/test_{commandlet}.py` as behavior changes.

## Contract

- Commandlet: `{commandlet}`
- Argument: `{argument}`
- Emits: `{topic}`
'''


def bundled_readme_md(commandlet: str, argument: str, topic: str, module: str) -> str:
    """Return a small README for generated bundled plugin packages."""
    entry = module.removeprefix("bywaf.plugins.")
    return f'''# {commandlet}

Generated Bywaf bundled-native plugin scaffold.

## Validate

```bash
python3 - <<'PY'
from bywaf.registry import PluginRegistry
PluginRegistry({{}}).load_package_entry("bywaf.plugins", "{entry}")
PY
```

Also update `bywaf/plugins/plugins.toml`, `docs/BUNDLED_PLUGIN_MANUAL.md`,
tests, and `CHANGELOG.md` before committing a real bundled plugin.

## Where To Put Code

- Put the commandlet's first implementation inside `{commandlet}(...)` in
  `__init__.py`.
- Replace the placeholder yielded payload with the structured fact this plugin
  owns.
- If the logic grows, move pure parsing/probing code into helper functions or
  split files such as `detect.py`, then keep `__init__.py` as the bundled
  commandlet entry point.
- Keep `bywaf.plugin.toml` synchronized with the commandlet: arguments,
  emitted topics, capabilities, database actions, and event schema fields.
- Add or update repository tests for the real behavior before adding the plugin
  to `bywaf/plugins/plugins.toml`.

## Contract

- Module: `{module}`
- Commandlet: `{commandlet}`
- Argument: `{argument}`
- Emits: `{topic}`
'''


def ensure_output_dir(path: Path, *, tests: bool) -> None:
    """Create an empty output directory or fail if it already has content."""
    if path.exists() and any(path.iterdir()):
        raise FileExistsError(f"{path} already exists and is not empty")
    path.mkdir(parents=True, exist_ok=True)
    if tests:
        path.joinpath("tests").mkdir(exist_ok=True)


def scaffold_plugin(args: argparse.Namespace) -> Path:
    """Write the scaffold and return the plugin directory."""
    output = default_output(args)
    output = output.expanduser()
    ensure_output_dir(output, tests=args.bundled is None)
    commandlet = args.commandlet or args.name
    topic = args.topic or f"{commandlet}.observed"
    description = args.description or f"Generated {commandlet} commandlet."
    module = bundled_module(args.bundled, commandlet) if args.bundled else ""

    if args.bundled:
        family_init = output.parent / "__init__.py"
        if not family_init.exists():
            family_init.write_text(f'"""Generated bundled plugin family: {args.bundled}."""\n', encoding="utf-8")
        output.joinpath("__init__.py").write_text(
            plugin_py(commandlet, args.argument, topic, bundled=True),
            encoding="utf-8",
        )
        output.joinpath("README.md").write_text(
            bundled_readme_md(commandlet, args.argument, topic, module),
            encoding="utf-8",
        )
    else:
        output.joinpath("plugin.py").write_text(plugin_py(commandlet, args.argument, topic), encoding="utf-8")
        output.joinpath("README.md").write_text(readme_md(commandlet, args.argument, topic), encoding="utf-8")
        output.joinpath("tests", f"test_{commandlet}.py").write_text(
            test_py(commandlet, args.argument, topic),
            encoding="utf-8",
        )
    output.joinpath("bywaf.plugin.toml").write_text(
        manifest_toml(
            commandlet,
            args.argument,
            topic,
            description=description,
            version=args.plugin_version,
            module=module,
        ),
        encoding="utf-8",
    )
    return output


def default_output(args: argparse.Namespace) -> Path:
    """Return the selected output directory."""
    if args.output is not None:
        return args.output
    if args.bundled:
        return Path("bywaf") / "plugins" / args.bundled / args.name
    return Path(args.name)


def bundled_module(family: str | None, commandlet: str) -> str:
    """Return the bundled import module for a generated package."""
    if family is None:
        return ""
    return f"bywaf.plugins.{family}.{commandlet}"


def build_parser() -> argparse.ArgumentParser:
    """Return the CLI parser."""
    parser = argparse.ArgumentParser(prog="scripts/plugin_new.py")
    parser.add_argument("name", type=lambda value: validate_identifier(value, label="name"))
    parser.add_argument(
        "--output",
        type=Path,
        help="Plugin directory to create. Defaults to ./NAME or bundled family path.",
    )
    parser.add_argument(
        "--bundled",
        type=lambda value: validate_identifier(value, label="bundled family"),
        help="Generate a bundled-native package under bywaf/plugins/FAMILY/NAME.",
    )
    parser.add_argument(
        "--commandlet",
        type=lambda value: validate_identifier(value, label="commandlet"),
        help="Commandlet name. Defaults to NAME.",
    )
    parser.add_argument(
        "--argument",
        type=lambda value: validate_identifier(value, label="argument"),
        default="target",
        help="Single positional argument name. Defaults to target.",
    )
    parser.add_argument(
        "--topic",
        type=validate_topic,
        help="Emitted event topic. Defaults to COMMANDLET.observed.",
    )
    parser.add_argument("--description", help="Commandlet description.")
    parser.add_argument("--plugin-version", default="0.1.0", help="Plugin manifest version.")
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        output = scaffold_plugin(args)
    except OSError as exc:
        parser.error(str(exc))
    print(f"Created plugin scaffold: {output}")
    if args.bundled:
        entry = f"{args.bundled}.{args.commandlet or args.name}"
        print(f"Validate bundled import: PluginRegistry({{}}).load_package_entry('bywaf.plugins', '{entry}')")
        print("Checklist: update bywaf/plugins/plugins.toml, bundled manual, tests, and CHANGELOG.md")
    else:
        print(f"Validate: python3 scripts/plugin_check.py {output} --strict-inference --llm-feedback")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
