"""Framework-owned event schema catalog.

This package-local module keeps the large built-in topic table separate from
the validation and object-conversion helpers exported by `bywaf.event.schemas`.
"""

from __future__ import annotations

from .defs import EventSchema, FieldSchema

EVENT_SCHEMAS: dict[str, EventSchema] = {
    "host.found": EventSchema(
        topic="host.found",
        summary="A host was observed alive or otherwise reachable.",
        fields=(
            FieldSchema("host", "str", True, "IP address or hostname used for follow-up work."),
            FieldSchema("ip", "str", False, "Concrete IP address when host is a DNS name or alias."),
            FieldSchema("name", "str", False, "Original DNS name or operator-provided name."),
            FieldSchema("status", "str", False, "Host state.", ("up", "reachable", "unknown")),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "name.resolved": EventSchema(
        topic="name.resolved",
        summary="A name resolved to one or more concrete addresses.",
        fields=(
            FieldSchema("name", "str", True, "Original hostname."),
            FieldSchema("host", "str", True, "Resolved address."),
            FieldSchema("resolver", "str", False, "Resolver or backend that produced the mapping."),
        ),
    ),
    "port.open": EventSchema(
        topic="port.open",
        summary="A network port was observed open on a host.",
        fields=(
            FieldSchema("host", "str", True, "Host or address where the port is open."),
            FieldSchema("port", "int", True, "Numeric port."),
            FieldSchema("protocol", "str", True, "Transport protocol.", ("tcp", "udp")),
            FieldSchema("state", "str", False, "Observed port state.", ("open", "open|filtered")),
            FieldSchema("service", "str", False, "Best-known service name or probe label."),
            FieldSchema("reason", "str", False, "Scanner reason, such as syn-ack."),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "http.endpoint": EventSchema(
        topic="http.endpoint",
        summary="A reachable HTTP or HTTPS endpoint.",
        fields=(
            FieldSchema("url", "str", True, "Canonical endpoint URL."),
            FieldSchema("host", "str", True, "Endpoint host."),
            FieldSchema("port", "int", True, "Endpoint port."),
            FieldSchema("scheme", "str", True, "HTTP scheme.", ("http", "https")),
            FieldSchema("status", "int", False, "HTTP status code."),
            FieldSchema("method", "str", False, "HTTP method used to probe the endpoint."),
            FieldSchema("server", "str", False, "Server header or equivalent banner."),
            FieldSchema("error", "str", False, "Probe error if endpoint metadata is partial."),
        ),
    ),
    "web.screenshotted_host": EventSchema(
        topic="web.screenshotted_host",
        summary="One host or endpoint has one or more screenshot artifacts.",
        fields=(
            FieldSchema("host", "str", True, "Endpoint host represented by the screenshots."),
            FieldSchema("urls", "list", True, "Endpoint URLs represented by the screenshots."),
            FieldSchema("screenshots", "list", True, "Screenshot artifact/file references."),
            FieldSchema("tool", "str", False, "Screenshot tool name."),
        ),
    ),
    "tcp.banner": EventSchema(
        topic="tcp.banner",
        summary="A TCP service banner or first response was captured.",
        fields=(
            FieldSchema("host", "str", True, "Host or address where the service responded."),
            FieldSchema("port", "int", True, "Numeric TCP port."),
            FieldSchema("protocol", "str", True, "Transport protocol.", ("tcp",)),
            FieldSchema("banner", "str", False, "Captured text response, truncated by the scanner."),
            FieldSchema("error", "str", False, "Connection or read error when no banner was captured."),
            FieldSchema("elapsed_ms", "int", False, "Elapsed probe time in milliseconds."),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "service.detected": EventSchema(
        topic="service.detected",
        summary="A normalized service classification for a host/port.",
        fields=(
            FieldSchema("host", "str", True, "Host where the service was observed."),
            FieldSchema("port", "int", True, "Numeric port."),
            FieldSchema("protocol", "str", True, "Transport protocol.", ("tcp", "udp")),
            FieldSchema("service", "str", True, "Service label such as ssh, http, tls, smb."),
            FieldSchema("product", "str", False, "Product name when known."),
            FieldSchema("version", "str", False, "Product version when known."),
            FieldSchema("source", "str", False, "Source topic or tool for the classification."),
            FieldSchema("confidence", "str", False, "Classification confidence.", ("low", "medium", "high")),
            FieldSchema("evidence", "str", False, "Short evidence used for classification."),
        ),
    ),
    "tls.certificate": EventSchema(
        topic="tls.certificate",
        summary="TLS certificate metadata observed from a network service.",
        fields=(
            FieldSchema("host", "str", True, "TLS endpoint host."),
            FieldSchema("port", "int", True, "TLS endpoint port."),
            FieldSchema("subject", "str", False, "Certificate subject."),
            FieldSchema("issuer", "str", False, "Certificate issuer."),
            FieldSchema("not_before", "str", False, "Certificate validity start."),
            FieldSchema("not_after", "str", False, "Certificate validity end."),
            FieldSchema("san", "list", False, "Subject alternative names."),
            FieldSchema("protocol", "str", False, "Negotiated TLS protocol version."),
            FieldSchema("cipher", "str", False, "Negotiated cipher suite."),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "http.path": EventSchema(
        topic="http.path",
        summary="One HTTP path response observed during path probing.",
        fields=(
            FieldSchema("url", "str", True, "Probed URL."),
            FieldSchema("host", "str", True, "Endpoint host."),
            FieldSchema("port", "int", True, "Endpoint port."),
            FieldSchema("path", "str", True, "Requested path."),
            FieldSchema("status", "int", False, "HTTP status code."),
            FieldSchema("title", "str", False, "HTML title when present."),
            FieldSchema("content_type", "str", False, "Response content type."),
            FieldSchema("length", "int", False, "Bounded response body length read."),
            FieldSchema("interesting", "bool", False, "Whether the path deserves operator attention."),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "web.waf.detected": EventSchema(
        topic="web.waf.detected",
        summary="A WAF or edge protection product fingerprint.",
        fields=(
            FieldSchema("url", "str", True, "Endpoint URL where the WAF signal was observed."),
            FieldSchema("host", "str", True, "Endpoint host."),
            FieldSchema("vendor", "str", True, "Detected vendor."),
            FieldSchema("product", "str", False, "Detected product."),
            FieldSchema("evidence", "str", False, "Header or response evidence."),
            FieldSchema("confidence", "str", False, "Detection confidence.", ("low", "medium", "high")),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "network.route.hop": EventSchema(
        topic="network.route.hop",
        summary="One hop observed while tracing a route to a target.",
        fields=(
            FieldSchema("target", "str", True, "Original trace target."),
            FieldSchema("hop", "int", True, "One-based hop number."),
            FieldSchema("host", "str", False, "Hop hostname or address text, when known."),
            FieldSchema("ip", "str", False, "Concrete hop IP address, when known."),
            FieldSchema("rtt_ms", "number", False, "First observed round-trip time in milliseconds."),
            FieldSchema("status", "str", False, "Hop observation status.", ("responded", "timeout")),
            FieldSchema("scanner", "str", False, "Tool or backend that produced the observation."),
        ),
    ),
    "smb.share.found": EventSchema(
        topic="smb.share.found",
        summary="An SMB share was observed on a host.",
        fields=(
            FieldSchema("host", "str", True, "SMB server host."),
            FieldSchema("share", "str", True, "Share name."),
            FieldSchema("ip", "str", False, "Concrete server IP address."),
            FieldSchema("port", "int", False, "SMB service port, usually 445."),
            FieldSchema("protocol", "str", False, "Protocol label, usually smb.", ("smb",)),
            FieldSchema("access", "str", False, "Observed access.", ("unknown", "none", "read", "write", "read_write")),
            FieldSchema("authenticated", "bool", False, "Whether authenticated credentials were used."),
            FieldSchema("remark", "str", False, "Share comment or tool-provided remark."),
        ),
    ),
    "finding.candidate": EventSchema(
        topic="finding.candidate",
        summary="A normalized finding-shaped observation that deserves review or correlation.",
        fields=(
            FieldSchema("title", "str", True, "Human-readable finding title."),
            FieldSchema("class", "str", True, "Stable Bywaf finding class."),
            FieldSchema("severity", "str", False, "Severity label."),
            FieldSchema("confidence", "str", False, "Confidence label."),
            FieldSchema("confidence_basis", "str", False, "Why the detector assigned that confidence."),
            FieldSchema("target", "dict", False, "Structured primary target."),
            FieldSchema("target_scope", "dict", False, "Finding grouping scope."),
            FieldSchema("affected", "list", False, "Affected resources."),
            FieldSchema("evidence", "str", False, "Short evidence summary."),
            FieldSchema("recommendation", "str", False, "Operator-facing remediation guidance."),
        ),
        notes=("Use bywaf.finding.candidate_payload(...) when possible.",),
    ),
    "finding.confirmed": EventSchema(
        topic="finding.confirmed",
        summary="A normalized finding with direct evidence strong enough to treat as confirmed risk.",
        fields=(
            FieldSchema("title", "str", True, "Human-readable finding title."),
            FieldSchema("class", "str", True, "Stable Bywaf finding class."),
            FieldSchema("severity", "str", False, "Severity label."),
            FieldSchema("confidence", "str", False, "Confidence label."),
            FieldSchema("confidence_basis", "str", False, "Why the detector assigned that confidence."),
            FieldSchema("status", "str", False, "Finding verification status.", ("confirmed",)),
            FieldSchema("target", "dict", False, "Structured primary target."),
            FieldSchema("target_scope", "dict", False, "Finding grouping scope."),
            FieldSchema("affected", "list", False, "Affected resources."),
            FieldSchema("evidence", "str", False, "Short evidence summary."),
            FieldSchema("recommendation", "str", False, "Operator-facing remediation guidance."),
        ),
        notes=("Use bywaf.finding.confirmed_payload(...) when possible.",),
    ),
    "artifact.attached": EventSchema(
        topic="artifact.attached",
        summary="An artifact body was attached to runtime provenance.",
        fields=(
            FieldSchema("artifact_id", "str", True, "Stable artifact serial."),
            FieldSchema("name", "str", True, "Artifact display name."),
            FieldSchema("content_type", "str", True, "MIME type or content label."),
            FieldSchema("sha256", "str", True, "SHA-256 digest of artifact body."),
            FieldSchema("size", "int", True, "Artifact body size in bytes."),
            FieldSchema("commandlet", "str", False, "Producing commandlet."),
            FieldSchema("job_id", "any", False, "Associated job id if available."),
            FieldSchema("pipeline_id", "str", False, "Associated pipeline serial if available."),
            FieldSchema("command_run_id", "str", False, "Associated step serial if available."),
            FieldSchema("note", "str", False, "Operator note or artifact note."),
        ),
    ),
}
